trav= ['London', 'Denmark', 'Juneau', 'Hong Kong', 'Sydney']
print (trav)
print (sorted(trav))
print (trav)
trav.reverse()
print (trav)
trav.reverse()
print (trav)
trav.sort(reverse=True)
print (trav)